---
- name: Cleanup
  hosts: localhost
  connection: local
  tasks:
    - name: "Include ansible-role-ec2-key"
      include_role:
        name: "ansible-role-ec2-key"
      vars:
        key_name: "GitHub Actions"
        remove_key: true
